name: Laravel test in docker

on: push
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Install Dependencies
        run: |
          php -v
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create cache boostrap
        run: mkdir -m 777 bootstrap/cache

      - name: Generate key
        run: php artisan key:generate

      - name: Migrate and seed database
        run: php artisan migrate --force --seed

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: testing
          DB_USERNAME: root
        run: vendor/bin/phpunit
